version: "3.8"
services:
  vister-db:
    container_name: vister-db
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'vister'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'wi4nt9rsbn'
  vister-rabbit:
    container_name: vister-rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672    
      - 15672:15672    
  # vister-importer:
  #   container_name: vister-importer
volumes:
  vister-db: {}